// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('1', async function() {
    await driver.get("http://localhost/newscode/register.php")
    await driver.manage().window().setRect({ width: 1296, height: 688 })
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("rozak")
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("rozak@codepolitan.com")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("12345678")
    await driver.findElement(By.id("confirmation_password")).click()
    await driver.findElement(By.id("confirmation_password")).sendKeys("12345678")
    await driver.findElement(By.css(".btn")).click()
    {
      const element = await driver.findElement(By.css(".btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.linkText("login")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("rozak@codepolitan.com")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("12345678")
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.css(".btn")).click()
    vars["win6280"] = await waitForWindow(2000)
    vars["root"] = await driver.getWindowHandle()
    await driver.switchTo().window(vars["win6280"])
    await driver.switchTo().window(vars["root"])
    await driver.findElement(By.linkText("About Us")).click()
    await driver.findElement(By.linkText("Contact Us")).click()
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("rozak")
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("rozak@codepolitan.com")
    await driver.findElement(By.id("message")).click()
    await driver.findElement(By.id("message")).sendKeys("Test")
    await driver.findElement(By.css(".mt-3")).click()
    await driver.findElement(By.linkText("Logout")).click()
  })
})
